import http from 'k6/http';
import { check, sleep } from 'k6';
import { Counter } from 'k6/metrics';

// Custom metrics
const errors = new Counter('errors');

// Morning rush pattern: Normal → Spike → Sustained → Return
export const options = {
    stages: [
        { duration: '1m', target: 5 },    // 08:00 - Normal baseline
        { duration: '30s', target: 50 },  // 11:00 - Morning spike (chef + manager rush)
        { duration: '2m', target: 50 },   // 11:00-13:00 - Sustained peak
        { duration: '30s', target: 10 },  // 13:00 - Lunch dip
        { duration: '1m', target: 5 },    // 14:00 - Return to baseline
    ],
    thresholds: {
        http_req_duration: ['p(95)<500', 'p(99)<1000'], // Realistic targets
        http_req_failed: ['rate<0.02'],
        errors: ['rate<0.01'],
    },
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3001';

// Test data - use 100 loadtest users across 3 tenants
// Generated by seed-users-heavy.ts
const TOTAL_USERS = 102; // Total users available (loadtest1 to loadtest102)
const PASSWORD = 'LoadTest123!';

const tenants = [
    { slug: 'test-pequeno', userStart: 1, userEnd: 34 },
    { slug: 'test-medio', userStart: 35, userEnd: 68 },
    { slug: 'test-grande', userStart: 69, userEnd: 102 },
];

// Build user pool
const users = [];
for (const tenant of tenants) {
    for (let i = tenant.userStart; i <= tenant.userEnd; i++) {
        users.push({
            email: `loadtest${i}@${tenant.slug}.com`,
            password: PASSWORD,
            tenantSlug: tenant.slug,
            // Simulate role distribution
            role: i % 3 === 0 ? 'manager' : (i % 2 === 0 ? 'chef' : 'staff'),
        });
    }
}

console.log(`📊 User pool: ${users.length} users across ${tenants.length} tenants`);

function login(user) {
    const res = http.post(`${BASE_URL}/api/auth/login`, JSON.stringify({
        email: user.email,
        password: user.password,
    }), {
        headers: { 'Content-Type': 'application/json' },
    });

    if (check(res, {
        'login successful': (r) => r.status === 200,
        'token received': (r) => r.json('token') !== undefined,
    })) {
        return res.json('token');
    }

    errors.add(1);
    return null;
}

// Simulate morning rush activities
export default function () {
    const user = users[Math.floor(Math.random() * users.length)];
    const token = login(user);

    if (!token) {
        sleep(1);
        return;
    }

    const headers = {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
    };

    // Activity mix based on role
    const activities = user.role === 'manager'
        ? ['dashboard', 'dashboard', 'products', 'recipes', 'menu'] // Managers check dashboards more
        : ['recipes', 'recipes', 'products', 'dashboard']; // Chefs work with recipes

    const activity = activities[Math.floor(Math.random() * activities.length)];

    switch (activity) {
        case 'dashboard':
            // Managers checking performance
            const dashRes = http.get(`${BASE_URL}/api/dashboard/stats`, { headers });
            check(dashRes, {
                '[Rush] Dashboard load': (r) => r.status === 200,
            });
            sleep(2); // Review time
            break;

        case 'products':
            // Browse products (pagination)
            const prodRes = http.get(`${BASE_URL}/api/products?page=1&limit=20`, { headers });
            check(prodRes, {
                '[Rush] Products list': (r) => r.status === 200,
            });
            sleep(1);
            break;

        case 'recipes':
            // Browse and view recipes
            const recipeListRes = http.get(`${BASE_URL}/api/recipes?page=1&limit=20`, { headers });
            check(recipeListRes, {
                '[Rush] Recipes list': (r) => r.status === 200,
            });

            // View a specific recipe (70% of time)
            if (Math.random() < 0.7 && recipeListRes.status === 200) {
                const recipes = recipeListRes.json('data');
                if (recipes && recipes.length > 0) {
                    const recipeId = recipes[0].id;
                    const recipeDetailRes = http.get(`${BASE_URL}/api/recipes/${recipeId}`, { headers });
                    check(recipeDetailRes, {
                        '[Rush] Recipe detail': (r) => r.status === 200,
                    });
                }
            }
            sleep(1.5);
            break;

        case 'menu':
            // Check menu items
            const menuRes = http.get(`${BASE_URL}/api/menu?page=1&limit=20`, { headers });
            check(menuRes, {
                '[Rush] Menu load': (r) => r.status === 200,
            });
            sleep(1);
            break;
    }

    sleep(Math.random() * 2); // Think time: 0-2s
}

export function handleSummary(data) {
    console.log('');
    console.log('🌅 Morning Rush Test Summary');
    console.log('========================================');
    console.log(`Peak VUs: ${data.metrics.vus_max.values.max}`);
    console.log(`Total Requests: ${data.metrics.http_reqs.values.count}`);
    console.log(`Failed Requests: ${data.metrics.http_req_failed.values.rate * 100}%`);
    console.log('');
    console.log('Response Times:');
    console.log(`  p50: ${data.metrics.http_req_duration.values['p(50)']}ms`);
    console.log(`  p95: ${data.metrics.http_req_duration.values['p(95)']}ms`);
    console.log(`  p99: ${data.metrics.http_req_duration.values['p(99)']}ms`);
    console.log('');

    const p95 = data.metrics.http_req_duration.values['p(95)'];
    const p99 = data.metrics.http_req_duration.values['p(99)'];

    if (p95 < 500) {
        console.log('✅ PASS: p95 < 500ms during peak load');
    } else {
        console.log(`❌ FAIL: p95 (${p95}ms) exceeded 500ms target`);
    }

    if (p99 < 1000) {
        console.log('✅ PASS: p99 < 1s during peak load');
    } else {
        console.log(`❌ FAIL: p99 (${p99}ms) exceeded 1s target`);
    }

    return {
        'stdout': '',
    };
}
